### PR TITLE
LugBot : Complete rewrite

### PR DESCRIPTION
**Pull request by msfjarvis**
* Moved configurables into bot.ini
* Migrated away from telepot
* Migrated to Python3.5
* Cleaned out idling hacks

### CODE REVIEW

**Review by sourabhtk37 — COMMENTED** [review]
are you handling message updates using updater?

**Comment by msfjarvis** [comment]
Yup

**Comment by sourabhtk37** [comment]
Cool,I will add it.

**Comment by msfjarvis** [comment]
You had to just merge this PR and in you went cooking god knows what shit on your telepot :confused:

**Comment by sourabhtk37** [comment]
GET BACK TO STUDYING.

**Comment by msfjarvis** [comment]
English and Computer Science next, meh

**Pull request merged**
